apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenwebapi14-deployment
  labels:
    app: zenwebapi14
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zenwebapi14
  template:
    metadata:
      labels:
        app: zenwebapi14
    spec:
      containers:
      - name: zenwebapi14
        image: ${IMAGE_URL}
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
